GET http://localhost:3001/
###
GET http://localhost:3001/admin
###
GET http://localhost:3001/admin/getAllUsers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWF0IjoxNzUwMTA3MzU1LCJleHAiOjE3NTAxMTA5NTV9.qF0bs8Y2IXtwxeUop79AYOP83zvRz6KaQD_WtwGtU4E
###
POST http://localhost:3001/user/signup
Content-Type: application/json

{
  "username": "User2",
  "password": "user1@123",
  "role": "admin",
  "firstName": "User",
  "lastName": "Two",
  "email": "user.two@example.com",
  "gender": "female"
}
###
POST http://localhost:3001/user/login
Content-Type: application/json

{
  "username": "User2",
  "password": "user1@123"
}
###
POST http://localhost:3001/user/deleteUser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwiaWF0IjoxNzUwMTA3NTA5LCJleHAiOjE3NTAxMTExMDl9.kKwn6cfmlgF1HMmcU5GNulMWEUh9N8bjJ2U_1H1vFEo

{
  "username": "User2"
}
###
POST http://localhost:3001/admin/deleteUserByAdmin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWF0IjoxNzUwMTA2ODY5LCJleHAiOjE3NTAxMTA0Njl9.TWmvMgGhB-SC3dMVLg3wioZZPMYgfi1A2dB8Xie1fTg

{
  "username": "User1"
}